---
services:
  # run postgres for proxy service to store observability metrics
  postgres:
    image: postgres:15
    env_file: .env
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    expose:
      - "${POSTGRES_CONTAINER_PORT}"
  # run redis for proxy service to cache responses
  redis:
    image: 'bitnami/redis:latest'
    env_file: .env
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}"
    expose:
      - "${REDIS_CONTAINER_PORT}"
  # run single validator fury node to provide a local fury network for development and testing of the proxy service
  fury:
    image: fury/fury:latest
    entrypoint: /docker/fury/fury-entrypoint.sh
    env_file: .env
    volumes:
      - ./docker/fury:/docker/fury
    ports:
      - "${FURY_HOST_COSMOS_RPC_PORT}:${FURY_CONTAINER_COSMOS_RPC_PORT}"
      - "${FURY_HOST_EVM_RPC_PORT}:${FURY_CONTAINER_EVM_RPC_PORT}"
    # expose ports for other services to be able to connect to within
    # the default docker-compose network
    expose:
      - "${FURY_CONTAINER_COSMOS_RPC_PORT}"
      - "${FURY_CONTAINER_EVM_RPC_PORT}"
  # run proxy service to observe, route, and scale requests to fury api endpoints
  proxy:
    build:
      dockerfile: local.Dockerfile
    env_file: .env
    ports:
      - "${PROXY_HOST_PORT}:${PROXY_CONTAINER_PORT}"
      - "${PROXY_CONTAINER_EVM_RPC_DATA_PORT}:${PROXY_CONTAINER_PORT}"
      - "${PROXY_HOST_DEBUG_PORT}:${PROXY_CONTAINER_DEBUG_PORT}"
    cap_add:
      - SYS_PTRACE # Allows for attaching debugger to process in this container
